export default function robots() {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: [
        "/topic/",
        "/producten/ring-video-deurbel",
        "/producten/aqara-doorbell-g410-grey",
        "/producten/aqara-doorbell-g410-black",
        "/producten/tapo-d205",
        "/producten/tapo-d235",
        "/producten/reolink-video-doorbell-wifi",
        "/producten/eufy-c30-2k-draadloze-videodeurbel-bundel",
        "/producten/tp-link-tapo-d210-slimme-video-deurbel",
        "/producten/tp-link-tapo-c520ws-2-pack-smart-battery-video-doo",
        "/producten/hue-secure-bedrade-videodeurbel",
        "/producten/hue-secure-bedrade-videodeurbel-chime",
        "/producten/eufy-indoor-cam",
        "/producten/tapo-c225",
        "/producten/eufy-solo-outdoor-cam",
        "/producten/reolink-poe-camera",
        "/producten/tapo-c200",
        "/producten/eve-cam",
        "/producten/tapo-c220-beveiligingscamera-binnen-2k-4mp-qhd-pan",
        "/producten/tp-link-tapo-c230",
        "/producten/tp-link-tapo-c500",
        "/producten/tp-link-tapo-c530ws",
        "/producten/nuki-smart-lock-4-pro",
        "/producten/yale-linus-smart-lock",
        "/producten/danalock-v3",
        "/producten/nuki-smart-lock-3-pro",
        "/producten/aqara-smart-lock-u200-lite",
        "/blog/wat-is-een-slimme-camera",
        "/blog/beste-slimme-deurbel",
        "/blog/ring-vs-tapo-deurbel",
        "/blog/eufy-vs-ring-camera",
        "/blog/slimme-deurbel-zonder-abonnement",
        "/blog/smart-home-beveiliging-tips",
        "/how-to/hoe-installeer-je-een-slimme-deurbel",
        "/how-to/hoe-installeer-je-een-tapo-camera",
      ],
    },
    sitemap: "https://www.slimhuiswonen.nl/sitemap.xml",
  };
}
